'use strict';
(()=>{if(!window.UCVM||typeof firebase==='undefined')return;const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(page!=='index.html')return;const {auth,db}=UCVM.init(),esc=UCVM.esc,banner=document.querySelector('.test-banner'),label=document.getElementById('ui-banner-label'),message=document.getElementById('ui-banner-message');if(!banner)return;let profile=null,messages=[{id:'release-afc-center',title:'AFC workflow update',body:'AFC approvals, availability lookup and verified electronic signatures are now available.',authorName:'UCVM',createdAt:'2026-09-12'}],unsub=null;
 label.textContent='INFORMATION CENTER';banner.setAttribute('aria-label','Information Center');let openBtn=document.getElementById('information-center-btn');if(!openBtn){openBtn=document.createElement('button');openBtn.id='information-center-btn';openBtn.textContent='View updates';openBtn.style.cssText='padding:3px 10px;border:1px solid #9a6700;border-radius:999px;background:#fff;color:#5e4b00;font-size:10.5px;font-weight:700';banner.insertBefore(openBtn,document.getElementById('auth-setup-btn'))}
 const time=v=>v?.toDate?v.toDate().toLocaleString('en-CA',{timeZone:'America/Edmonton'}):String(v||'');
 function render(){label.textContent='INFORMATION CENTER';const latest=messages[0];message.textContent=latest?`${latest.title}: ${latest.body}`:'No current announcements.';openBtn.textContent=`View updates${messages.length?` (${messages.length})`:''}`}
 function show(){const modal=document.getElementById('modal');if(!modal)return;const can=UCVM.general(profile);modal.innerHTML=`<div class="modal-box workflow-modal-box"><div class="modal-header"><div class="modal-title">Information Center</div><div class="modal-subtitle">Latest timetable, workflow and operational updates</div></div><div class="modal-body">${messages.map(x=>`<article class="workflow-card"><strong>${esc(x.title)}</strong><div class="workflow-note">${esc(time(x.createdAt))} · ${esc(x.authorName||'UCVM')}</div><p>${esc(x.body)}</p></article>`).join('')||'<p>No current announcements.</p>'}${can?`<form id="info-form" class="workflow-card"><h3>Publish an update</h3><label class="form-field"><span class="form-label">Title</span><input class="form-input" name="title" maxlength="80" required></label><label class="form-field"><span class="form-label">Message</span><textarea class="form-input" name="body" maxlength="500" rows="4" required></textarea></label><button class="btn btn-primary">Publish</button></form>`:''}</div><div class="modal-footer"><span class="workflow-note">All signed-in users can read these updates.</span><button class="btn btn-secondary" data-close>Close</button></div></div>`;modal.classList.add('open');modal.querySelector('[data-close]').onclick=()=>{modal.classList.remove('open');modal.innerHTML=''};const form=modal.querySelector('#info-form');if(form)form.onsubmit=async e=>{e.preventDefault();const d=new FormData(form),item={id:crypto.randomUUID(),title:String(d.get('title')).trim(),body:String(d.get('body')).trim(),authorUid:auth.currentUser.uid,authorName:profile.name||auth.currentUser.email||'',createdAt:new Date().toISOString()};await db.doc('public_info/information_center').set({messages:[item,...messages].slice(0,10),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:auth.currentUser.uid},{merge:true});show()}}
 openBtn.onclick=show;auth.onAuthStateChanged(async u=>{if(unsub){unsub();unsub=null}profile=null;if(!u)return;try{const snap=window.UCVM_PAGE_DATA?.profileSnapshot?await window.UCVM_PAGE_DATA.profileSnapshot(u.uid):await db.doc(`users/${u.uid}`).get();profile=snap.data()||{};unsub=db.doc('public_info/information_center').onSnapshot(s=>{messages=Array.isArray(s.data()?.messages)&&s.data().messages.length?s.data().messages:[{id:'release-afc-center',title:'AFC workflow update',body:'AFC approvals, availability lookup and verified electronic signatures are now available.',authorName:'UCVM',createdAt:'2026-09-12'}];render()},()=>{messages=[];render()})}catch(_){}});
})();

