'use strict';
(()=>{const {auth,db}=UCVM.init(),$=id=>document.getElementById(id);let me,completed=false;
 // mustChangePassword is UI guidance, NOT a security control. The account holder
 // clears it themselves in the same write that changes the password, so it must
 // not be cited in any security argument. Replacing it with a trusted invitation
 // or institutional SSO is tracked in the audit report (R09).
 const MIN_PASSWORD_LENGTH=8;
 function passwordProblem(next,current){if(next.length<MIN_PASSWORD_LENGTH)return `Choose a password of at least ${MIN_PASSWORD_LENGTH} characters.`;if(next===current)return 'Choose a password that differs from your current one.';if(/^(.)\1+$/.test(next))return 'Choose a password that is not a single repeated character.';return '';}
 $('signout').onclick=()=>auth.signOut();auth.onAuthStateChanged(async u=>{if(!u){if(completed){$('identity').textContent='Signed out';return}location.replace('index.html');return}try{me=(await db.doc(`users/${u.uid}`).get()).data();if(!me?.active)throw Error('This account is inactive.');$('identity').textContent=me.name||u.email;if(me.mustChangePassword)$('password-note').textContent='Before continuing, replace your temporary password with a new password of at least 8 characters.';$('content').hidden=false}catch(e){$('status').textContent=e.message}});
 $('password-form').onsubmit=async ev=>{ev.preventDefault();const next=$('password-new').value;if(next!==$('password-confirm').value){$('status').textContent='The new passwords do not match.';return}const problem=passwordProblem(next,$('password-current').value);if(problem){$('status').textContent=problem;return}const b=ev.target.querySelector('button');b.disabled=true;try{const user=auth.currentUser;await user.reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential(user.email,$('password-current').value));await user.updatePassword(next);await db.doc(`users/${user.uid}`).update({mustChangePassword:false,passwordChangedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});completed=true;ev.target.reset();$('content').hidden=true;$('status').textContent='Password changed. Please sign in again with your new password.';await auth.signOut()}catch(e){$('status').textContent=e.message}finally{b.disabled=false}};
})();
