'use strict';
(()=>{const {auth,db}=UCVM.init(),$=id=>document.getElementById(id);let me=null,completed=false;
 // mustChangePassword is UI guidance, NOT a security control. The account holder
 // clears it themselves in the same write that changes the password, so it must
 // not be cited in any security argument. Replacing it with a trusted invitation
 // or institutional SSO is tracked in the audit report (R09).
 const MIN_PASSWORD_LENGTH=8;
 const RESET_SENT_MESSAGE='If an account exists for that email, Firebase has sent password-reset instructions.';
 function passwordProblem(next,current){if(next.length<MIN_PASSWORD_LENGTH)return `Choose a password of at least ${MIN_PASSWORD_LENGTH} characters.`;if(next===current)return 'Choose a password that differs from your current one.';if(/^(.)\1+$/.test(next))return 'Choose a password that is not a single repeated character.';return '';}
 function errorCode(error){return String(error?.code||'').toLowerCase()}
 function changePasswordError(error){const code=errorCode(error);if(['auth/wrong-password','auth/invalid-credential','auth/invalid-login-credentials'].includes(code))return 'The current password is incorrect.';if(code==='auth/weak-password')return `Choose a password of at least ${MIN_PASSWORD_LENGTH} characters.`;if(code==='auth/too-many-requests')return 'Too many password attempts. Try again later or use the reset-email option.';if(code==='auth/network-request-failed')return 'The password service could not be reached. Check your connection and try again.';return error?.message||'Password change failed.'}
 function resetPasswordError(error){const code=errorCode(error);if(code==='auth/user-not-found')return RESET_SENT_MESSAGE;if(code==='auth/invalid-email')return 'Enter a valid email address.';if(code==='auth/too-many-requests')return 'Too many reset attempts. Try again later.';if(code==='auth/network-request-failed')return 'The password service could not be reached. Check your connection and try again.';return error?.message||'Password reset email could not be sent.'}
 function passwordProviderAvailable(user){if(!user?.email)return false;const providers=Array.isArray(user.providerData)?user.providerData.map(row=>row?.providerId).filter(Boolean):[];return !providers.length||providers.includes('password')}
 function showReset(user=null){const section=$('password-reset-section'),input=$('password-reset-email');if(section)section.hidden=false;if(user?.email&&input&&!input.value)input.value=user.email}
 function setSignedOut(){me=null;$('identity').textContent=completed?'Signed out':'Not signed in';$('signout').hidden=true;$('password-change-section').hidden=true;$('password-change-unavailable').hidden=true;showReset(null)}
 $('signout').onclick=()=>auth.signOut();
 auth.onAuthStateChanged(async u=>{showReset(u);$('signout').hidden=!u;if(!u){setSignedOut();return}try{me=(await db.doc(`users/${u.uid}`).get()).data();if(!me?.active)throw Error('This account is inactive.');$('identity').textContent=me.name||u.email||u.phoneNumber||'Signed in';const canChange=passwordProviderAvailable(u);$('password-change-section').hidden=!canChange;$('password-change-unavailable').hidden=canChange;if(!canChange)$('password-change-unavailable').textContent=u.email?'This account does not use an email/password credential. Use the sign-in method linked to this account.':'This account does not have an email/password credential to change.';if(me.mustChangePassword&&canChange)$('password-note').textContent='Before continuing, replace your temporary password with a new password of at least 8 characters.';}catch(e){$('password-change-section').hidden=true;$('password-change-unavailable').hidden=true;$('status').textContent=e.message}});
 $('password-reset-form').onsubmit=async ev=>{ev.preventDefault();const email=String($('password-reset-email').value||'').trim().toLowerCase(),b=ev.target.querySelector('button');if(!email||!email.includes('@')){$('status').textContent='Enter a valid email address.';return}b.disabled=true;try{await auth.sendPasswordResetEmail(email);$('status').textContent=RESET_SENT_MESSAGE;ev.target.reset();if(auth.currentUser?.email)$('password-reset-email').value=auth.currentUser.email}catch(e){$('status').textContent=resetPasswordError(e)}finally{b.disabled=false}};
 $('password-form').onsubmit=async ev=>{ev.preventDefault();const next=$('password-new').value;if(next!==$('password-confirm').value){$('status').textContent='The new passwords do not match.';return}const problem=passwordProblem(next,$('password-current').value);if(problem){$('status').textContent=problem;return}const b=ev.target.querySelector('button');b.disabled=true;const user=auth.currentUser;try{if(!passwordProviderAvailable(user))throw Error('This account does not use an email/password credential.');await user.reauthenticateWithCredential(firebase.auth.EmailAuthProvider.credential(user.email,$('password-current').value));await user.updatePassword(next)}catch(e){$('status').textContent=changePasswordError(e);b.disabled=false;return}let profileUpdated=true;try{await db.doc(`users/${user.uid}`).update({mustChangePassword:false,passwordChangedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(_){profileUpdated=false}completed=true;ev.target.reset();$('password-change-section').hidden=true;let signedOut=true;try{await auth.signOut()}catch(_){signedOut=false}$('status').textContent=!profileUpdated?'Password changed successfully, but the account profile could not be updated. Please sign in again with your new password.':!signedOut?'Password changed successfully. Please sign out manually, then sign in again with your new password.':'Password changed. Please sign in again with your new password.';b.disabled=false};
})();
