'use strict';
window.UCVM_SIGNATURE=(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const hash=async text=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');
 function imageData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('Could not read the signature image.'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(Error('Please select a valid PNG or JPEG image.'));img.onload=()=>{const scale=Math.min(1,600/img.width,180/img.height),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)})}
 function capture({name='',email='',uid='',title='Electronic signature'}={}){return new Promise(resolve=>{
  const layer=document.createElement('div');layer.className='ucvm-signature-layer';layer.innerHTML=`<style>.ucvm-signature-layer{position:fixed;inset:0;z-index:10000;background:#0008;display:grid;place-items:center;padding:18px}.ucvm-signature-card{width:min(680px,96vw);max-height:94vh;overflow:auto;background:#fff;color:#111827;border-radius:8px;border-top:5px solid #d6001c;box-shadow:0 20px 70px #0006;padding:20px}.ucvm-signature-tabs{display:flex;gap:7px;margin:14px 0}.ucvm-signature-tabs button,.ucvm-signature-actions button{padding:8px 13px;border:1px solid #cbd5e1;border-radius:4px;background:#fff}.ucvm-signature-tabs button.active,.ucvm-signature-actions [data-sign]{background:#d6001c;border-color:#d6001c;color:#fff}.ucvm-signature-pane{display:none}.ucvm-signature-pane.active{display:block}.ucvm-signature-pane input{width:100%;padding:9px;border:1px solid #cbd5e1;border-radius:4px}.ucvm-signature-canvas{width:100%;height:180px;border:1px solid #94a3b8;background:#fff;touch-action:none}.ucvm-signature-evidence{font-size:11px;color:#64748b;margin:10px 0}.ucvm-signature-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.ucvm-signature-error{color:#b91c1c;font-size:12px}</style><div class="ucvm-signature-card" role="dialog" aria-modal="true"><h2>${esc(title)}</h2><p>Choose how to sign. The final record includes your account, signing time, method and a verification fingerprint.</p><div class="ucvm-signature-tabs"><button type="button" data-mode="typed" class="active">Type</button><button type="button" data-mode="drawn">Draw</button><button type="button" data-mode="uploaded">Upload</button></div><div class="ucvm-signature-pane active" data-pane="typed"><label>Full name<input id="ucvm-signature-name" value="${esc(name)}" autocomplete="name"></label></div><div class="ucvm-signature-pane" data-pane="drawn"><canvas class="ucvm-signature-canvas" width="600" height="180"></canvas><button type="button" data-clear>Clear drawing</button></div><div class="ucvm-signature-pane" data-pane="uploaded"><label>PNG or JPEG signature image<input id="ucvm-signature-file" type="file" accept="image/png,image/jpeg"></label></div><label style="display:flex;gap:8px;margin-top:14px"><input id="ucvm-signature-attest" type="checkbox"> I confirm this is my electronic signature and I intend to sign this record.</label><div class="ucvm-signature-evidence">Account: ${esc(email||uid)} · Time is recorded when you select Sign.</div><div class="ucvm-signature-error"></div><div class="ucvm-signature-actions"><button type="button" data-cancel>Cancel</button><button type="button" data-sign>Sign</button></div></div>`;
  document.body.appendChild(layer);let mode='typed',drawing=false,dirty=false;const canvas=layer.querySelector('canvas'),ctx=canvas.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111827';
  const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};
  canvas.onpointerdown=e=>{drawing=true;dirty=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke()};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;
  layer.querySelector('[data-clear]').onclick=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);dirty=false};
  layer.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;layer.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));layer.querySelectorAll('[data-pane]').forEach(x=>x.classList.toggle('active',x.dataset.pane===mode))});
  const finish=v=>{layer.remove();resolve(v)};layer.querySelector('[data-cancel]').onclick=()=>finish(null);
  layer.querySelector('[data-sign]').onclick=async()=>{const error=layer.querySelector('.ucvm-signature-error'),signedName=layer.querySelector('#ucvm-signature-name').value.trim()||name.trim();error.textContent='';try{if(!layer.querySelector('#ucvm-signature-attest').checked)throw Error('Confirm the signature attestation.');if(!signedName)throw Error('Enter the signer name.');let imageDataUrl='';if(mode==='drawn'){if(!dirty)throw Error('Draw your signature first.');imageDataUrl=canvas.toDataURL('image/png')}if(mode==='uploaded'){const file=layer.querySelector('#ucvm-signature-file').files?.[0];if(!file)throw Error('Choose a signature image.');imageDataUrl=await imageData(file)}const signedAt=new Date().toISOString(),fingerprint=await hash([mode,signedName,uid,email,signedAt,imageDataUrl].join('|'));finish({mode,name:signedName,uid,email,signedAt,account:email||uid,attested:true,fingerprint,imageDataUrl})}catch(e){error.textContent=e.message}};
 })}
 return{capture};
})();
