'use strict';
const {test,before,beforeEach,after}=require('node:test');
const fs=require('node:fs');
const path=require('node:path');
const enabled=!!process.env.FIRESTORE_EMULATOR_HOST;let env;
const check=(name,fn)=>test('office timetable: '+name,{skip:!enabled},fn);
const source={course:'505',courseName:'Clinical Skills III',year:3,semester:'winter',week:8,date:'2027-03-22',start:'14:45',end:'16:15',timeUnknown:false,type:'LAB',topic:'Suturing',room:'CSB 116',instructor:'Jane Smith',assignments:[{ucid:'f1',name:'Jane Smith',doeCredit:.5}],sourceSystem:'Test'};
const calendar={sessionId:'s1',course:'505',courseName:'Clinical Skills III',year:3,semester:'winter',week:8,date:'2027-03-22',start:'14:45',end:'16:15',timeUnknown:false,type:'LAB',topic:'Suturing',room:'CSB 116',instructor:'Jane Smith',instructorNames:['Jane Smith']};
before(async()=>{if(!enabled)return;const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');env=await initializeTestEnvironment({projectId:'demo-ucvm-office-timetable',firestore:{rules:fs.readFileSync(path.join(__dirname,'../firestore.rules'),'utf8')}});await env.clearFirestore();await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();for(const [uid,role] of [['adc','adc'],['lab','lab'],['adfa','adfa_regular']])await db.doc(`users/${uid}`).set({role,active:true,mustChangePassword:false,email:uid+'@example.test'});});});
beforeEach(async()=>{if(!enabled)return;await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();await db.doc('sessions/s1').set(source);await db.doc('calendar_sessions/s1').set(calendar);});});
after(async()=>{if(env)await env.cleanup();});
function pairedUpdate(db,sourcePatch,calendarPatch){const {serverTimestamp}=require('firebase/firestore');const batch=db.batch(),stamp=serverTimestamp();batch.update(db.doc('sessions/s1'),{...sourcePatch,updatedBy:'adc',updatedByName:'ADC',updatedAt:stamp});batch.set(db.doc('calendar_sessions/s1'),{...calendar,...calendarPatch});batch.set(db.collection('session_change_log').doc(),{action:'update',sessionId:'s1',course:String(calendarPatch.course||calendar.course),date:String(calendarPatch.date||calendar.date),topic:String(calendarPatch.topic||calendar.topic),instructors:[],changes:[],changedBy:'adc',changedByName:'ADC',changedByEmail:'',changedAt:stamp});return batch.commit();}
check('ADC may update owned public fields only when source calendar and audit are paired',async()=>{const {assertSucceeds}=require('@firebase/rules-unit-testing'),db=env.authenticatedContext('adc').firestore();await assertSucceeds(pairedUpdate(db,{room:'CSB 117'},{room:'CSB 117'}));});
check('ADC cannot change Instructor or LAB Topic even in a paired write',async()=>{const {assertFails}=require('@firebase/rules-unit-testing'),db=env.authenticatedContext('adc').firestore();await assertFails(pairedUpdate(db,{instructor:'Someone Else'},{instructor:'Someone Else',instructorNames:['Someone Else']}));await assertFails(pairedUpdate(db,{topic:'Private Lab Change'},{topic:'Private Lab Change'}));});
check('ADC source-only and calendar-only changes are denied',async()=>{const {assertFails}=require('@firebase/rules-unit-testing'),{serverTimestamp}=require('firebase/firestore'),db=env.authenticatedContext('adc').firestore();await assertFails(db.doc('sessions/s1').update({room:'Unpaired',updatedBy:'adc',updatedByName:'ADC',updatedAt:serverTimestamp()}));await assertFails(db.doc('calendar_sessions/s1').update({room:'Unpaired'}));});
check('LAB may change LAB topic and group assignment only in a paired write',async()=>{const {assertSucceeds,assertFails}=require('@firebase/rules-unit-testing'),{serverTimestamp}=require('firebase/firestore'),db=env.authenticatedContext('lab').firestore();let stamp=serverTimestamp(),batch=db.batch();batch.update(db.doc('sessions/s1'),{topic:'New LAB Topic',labGroupIds:['g-a'],updatedBy:'lab',updatedByName:'LAB',updatedAt:stamp});batch.set(db.doc('calendar_sessions/s1'),{...calendar,topic:'New LAB Topic',labGroupIds:['g-a']});batch.set(db.collection('session_change_log').doc(),{action:'update',sessionId:'s1',course:'505',date:calendar.date,topic:'New LAB Topic',instructors:[],changes:[],changedBy:'lab',changedByName:'LAB',changedByEmail:'',changedAt:stamp});await assertSucceeds(batch.commit());stamp=serverTimestamp();batch=db.batch();batch.update(db.doc('sessions/s1'),{room:'Forbidden',updatedBy:'lab',updatedByName:'LAB',updatedAt:stamp});batch.set(db.doc('calendar_sessions/s1'),{...calendar,topic:'New LAB Topic',labGroupIds:['g-a'],room:'Forbidden'});await assertFails(batch.commit());});
check('ADC may create an unassigned LAB only with TBD topic and paired calendar',async()=>{const {assertSucceeds,assertFails}=require('@firebase/rules-unit-testing'),{serverTimestamp}=require('firebase/firestore'),db=env.authenticatedContext('adc').firestore();const stamp=serverTimestamp(),id='adc-new',newSource={...source,type:'LAB',topic:'TBD',instructor:'',assignments:[],updatedBy:'adc',updatedByName:'ADC',updatedAt:stamp},newCalendar={...calendar,sessionId:id,type:'LAB',topic:'TBD',instructor:'',instructorNames:[]};let batch=db.batch();batch.set(db.doc(`sessions/${id}`),newSource);batch.set(db.doc(`calendar_sessions/${id}`),newCalendar);batch.set(db.collection('session_change_log').doc(),{action:'create',sessionId:id,course:'505',date:calendar.date,topic:'TBD',instructors:[],changes:[],changedBy:'adc',changedByName:'ADC',changedByEmail:'',changedAt:stamp});await assertSucceeds(batch.commit());const badId='adc-bad';batch=db.batch();batch.set(db.doc(`sessions/${badId}`),{...newSource,topic:'Not TBD'});batch.set(db.doc(`calendar_sessions/${badId}`),{...newCalendar,sessionId:badId,topic:'Not TBD'});await assertFails(batch.commit());});
