'use strict';
const {test,before,after}=require('node:test');
const fs=require('node:fs'),path=require('node:path');
const enabled=!!process.env.FIRESTORE_EMULATOR_HOST;
let env;
const users={general:{role:'adfa_general',name:'General'},regular:{role:'adfa_regular',name:'Regular'},hicc:{role:'hicc',name:'HICC',facultyId:'f1'},visc:{role:'visc',name:'VISC',facultyId:'f2'},member:{role:'faculty',name:'Member',facultyId:'f3'},temporary:{role:'faculty',name:'Temporary',mustChangePassword:true},disabled:{role:'faculty',name:'Disabled',active:false}};
before(async()=>{if(!enabled)return;const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');env=await initializeTestEnvironment({projectId:'demo-ucvm-access',firestore:{rules:fs.readFileSync(path.join(__dirname,'../firestore.rules'),'utf8')}});await env.clearFirestore();await env.withSecurityRulesDisabled(async context=>{const admin=context.firestore();for(const [uid,p]of Object.entries(users))await admin.doc(`users/${uid}`).set({active:true,email:`${uid}@ucvm.test`,...p});for(let i=1;i<=3;i++)await admin.doc(`faculty/f${i}`).set({preferredFullName:`Faculty ${i}`,email:`member${i}@ucvm.test`});await admin.doc('sessions/s1').set({course:'301',topic:'Original',date:'2026-09-08',facultyIds:['f1'],assignments:[{ucid:'f1'}],updatedBy:'general'})})});
after(async()=>{if(env)await env.cleanup()});
const check=(name,fn)=>test(name,{skip:!enabled},fn);

check('rules deny anonymous, disabled, and temporary-password session access',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{getDoc,doc}=require('firebase/firestore');await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'sessions/s1')));for(const uid of ['disabled','temporary'])await assertFails(getDoc(doc(env.authenticatedContext(uid).firestore(),'sessions/s1')));await assertSucceeds(getDoc(doc(env.authenticatedContext('member').firestore(),'sessions/s1')))});
check('roles and logs cannot be forged; faculty can read only their linked profile and cannot write sessions',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{setDoc,doc,deleteDoc,getDoc}=require('firebase/firestore');for(const uid of ['general','regular','hicc','visc','member']){const db=env.authenticatedContext(uid).firestore();await assertFails(setDoc(doc(db,`users/${uid}`),{active:true,role:'adfa_general'}));await assertFails(setDoc(doc(db,'audit_events/forged'),{changedBy:uid}))}for(const [uid,own,other] of [['hicc','f1','f2'],['visc','f2','f1'],['member','f3','f1']]){const db=env.authenticatedContext(uid).firestore();await assertFails(deleteDoc(doc(db,'sessions/s1')));await assertSucceeds(getDoc(doc(db,`faculty/${own}`)));await assertFails(getDoc(doc(db,`faculty/${other}`)))}await assertSucceeds(getDoc(doc(env.authenticatedContext('regular').firestore(),'faculty/f1')))});
check('ADFA direct writes are allowed, actor spoofing and client audit markers are blocked',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,setDoc,deleteDoc,serverTimestamp}=require('firebase/firestore');const db=env.authenticatedContext('regular').firestore();await assertSucceeds(setDoc(doc(db,'sessions/admin-create'),{course:'301',topic:'Admin add',facultyIds:[],updatedBy:'regular',updatedAt:serverTimestamp()}));await assertFails(setDoc(doc(db,'sessions/forged-actor'),{topic:'Forged actor',updatedBy:'general',updatedAt:serverTimestamp()}));await assertFails(setDoc(doc(db,'sessions/forged-marker'),{topic:'Forged marker',updatedBy:'regular',updatedAt:serverTimestamp(),auditEventId:'fake'}));await assertFails(setDoc(doc(db,'sessions/admin-create'),{auditEventId:'fake',updatedBy:'regular',updatedAt:serverTimestamp()},{merge:true}));await assertSucceeds(deleteDoc(doc(db,'sessions/admin-create')))});
check('multi-session batches require an administrator actor marker and allow paired logs',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,writeBatch,serverTimestamp}=require('firebase/firestore');const regular=env.authenticatedContext('regular').firestore(),member=env.authenticatedContext('member').firestore();const allowed=writeBatch(regular);allowed.update(doc(regular,'sessions/s1'),{topic:'Batch edit',updatedBy:'regular',updatedAt:serverTimestamp()});allowed.set(doc(regular,'session_change_log/batch-s1'),{sessionId:'s1',action:'batch_update',changedBy:'regular',changedAt:serverTimestamp()});await assertSucceeds(allowed.commit());const noActor=writeBatch(regular);noActor.update(doc(regular,'sessions/s1'),{topic:'Missing actor'});await assertFails(noActor.commit());const facultyBatch=writeBatch(member);facultyBatch.update(doc(member,'sessions/s1'),{topic:'Faculty edit',updatedBy:'member'});facultyBatch.set(doc(member,'session_change_log/member-s1'),{sessionId:'s1',action:'batch_update',changedBy:'member',changedAt:serverTimestamp()});await assertFails(facultyBatch.commit())});
check('bulk imports and public information writes are limited to ADFA General',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,setDoc,getDoc,serverTimestamp}=require('firebase/firestore');const regular=env.authenticatedContext('regular').firestore(),general=env.authenticatedContext('general').firestore(),member=env.authenticatedContext('member').firestore();await assertFails(setDoc(doc(regular,'faculty/f1'),{awayFromCampusRecords:[],awayFromCampusImportedBy:'regular',updatedBy:'regular'},{merge:true}));await assertSucceeds(setDoc(doc(general,'faculty/f1'),{awayFromCampusRecords:[],awayFromCampusImportedBy:'general',updatedBy:'general'},{merge:true}));await assertFails(setDoc(doc(regular,'sessions/s1'),{sourceWorkbook:'bulk.json',bulkImportedBy:'regular',updatedBy:'regular'},{merge:true}));await assertSucceeds(setDoc(doc(general,'public_info/information_center'),{messages:[{id:'m1',title:'Update',body:'Message'}],updatedBy:'general',updatedAt:serverTimestamp()}));await assertSucceeds(getDoc(doc(member,'public_info/information_center')));await assertFails(setDoc(doc(regular,'public_info/information_center'),{messages:[],updatedBy:'regular',updatedAt:serverTimestamp()}))});
check('derived settings can be maintained only by administrators',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,setDoc,getDoc}=require('firebase/firestore');const regular=env.authenticatedContext('regular').firestore(),member=env.authenticatedContext('member').firestore();await assertSucceeds(setDoc(doc(regular,'settings/faculty_index'),{entries:[]}));await assertSucceeds(getDoc(doc(regular,'settings/faculty_index')));await assertFails(setDoc(doc(member,'settings/faculty_index'),{entries:[]}));await assertFails(getDoc(doc(member,'settings/faculty_index')))});
check('Owner can store validated faculty role arrays but cannot grant access through them',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,setDoc,serverTimestamp}=require('firebase/firestore');const db=env.authenticatedContext('general').firestore(),base={name:'Faculty 1',email:'member1@ucvm.test',role:'hicc',facultyId:'f1',active:true,mustChangePassword:true,updatedBy:'general',updatedByName:'General',updatedAt:serverTimestamp(),createdAt:serverTimestamp()};await assertSucceeds(setDoc(doc(db,'users/new-faculty'),{...base,facultyRoles:['hicc','visc','faculty']}));await assertFails(setDoc(doc(db,'users/invalid-faculty'),{...base,email:'invalid@ucvm.test',facultyRoles:['owner','faculty']}))});
check('AFC contact validation accepts bounded values and rejects blank or oversized fields',async()=>{const {assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,setDoc,serverTimestamp}=require('firebase/firestore');const applicantDb=env.authenticatedContext('member').firestore(),validRequest={requesterUid:'member',facultyId:'f3',reportToUid:'',status:'pending_admin',applicantSignature:{uid:'member',attested:true},submittedAt:serverTimestamp(),updatedAt:serverTimestamp(),contactAddress:'2500 University Drive NW',contactPhone:'403-555-1212'};await assertSucceeds(setDoc(doc(applicantDb,'afc_requests/new'),validRequest));await assertFails(setDoc(doc(applicantDb,'afc_requests/blank'),{...validRequest,contactPhone:' '}));await assertFails(setDoc(doc(applicantDb,'afc_requests/address-too-long'),{...validRequest,contactAddress:'a'.repeat(501)}));await assertFails(setDoc(doc(applicantDb,'afc_requests/phone-too-long'),{...validRequest,contactPhone:'1'.repeat(51)}))});
check('legacy AFC requests without contact details remain approvable',async()=>{const {assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,setDoc,updateDoc,serverTimestamp}=require('firebase/firestore');await env.withSecurityRulesDisabled(async context=>{await setDoc(doc(context.firestore(),'afc_requests/legacy'),{requesterUid:'member',facultyId:'f3',reportToUid:'',status:'pending_admin'})});const adminDb=env.authenticatedContext('regular').firestore(),approvalPatch={status:'approved',adminSignature:{uid:'regular'},pdfChunkCount:1,pdfSha256:'legacy-pdf',pdfByteLength:1,approvedAt:serverTimestamp(),updatedAt:serverTimestamp()};await assertSucceeds(updateDoc(doc(adminDb,'afc_requests/legacy'),approvalPatch))});