'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const project='tester-teaching',base=`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents`;
const cfg=JSON.parse(fs.readFileSync(path.join(process.env.USERPROFILE,'.config','configstore','firebase-tools.json'),'utf8')),token=cfg.tokens?.access_token;if(!token)throw Error('Firebase CLI access token unavailable.');
const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers,...opt.headers}});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.status===204?{}:r.json()}
const val=v=>v?.stringValue??v?.booleanValue??(v?.integerValue!==undefined?Number(v.integerValue):null),field=(d,k)=>val(d.fields?.[k]);
async function list(col){let out=[],pageToken='';do{const u=new URL(`${base}/${col}`);u.searchParams.set('pageSize','300');if(pageToken)u.searchParams.set('pageToken',pageToken);const j=await api(u);out.push(...(j.documents||[]));pageToken=j.nextPageToken||''}while(pageToken);return out}
const sv=x=>({stringValue:String(x)}),bv=x=>({booleanValue:!!x}),iv=x=>({integerValue:String(x)}),tv=x=>({timestampValue:x});
(async()=>{try{await api(`${base}/settings/migrations_assigned_ad_removed`);console.log(JSON.stringify({ok:true,alreadyDone:true,removed:0,routed:0}));return}catch(e){if(!String(e.message).startsWith('404 '))throw e}
 const [faculty,users]=await Promise.all([list('faculty'),list('users')]),owner=users.find(u=>['adfa_general','owner'].includes(field(u,'role'))&&field(u,'active')===true);if(!owner)throw Error('No active ADFA General profile found.');const actorUid=owner.name.split('/').pop(),actorName=field(owner,'name')||field(owner,'email')||actorUid;
 const uidByFaculty=new Map(users.filter(u=>field(u,'active')===true&&field(u,'facultyId')).map(u=>[String(field(u,'facultyId')),u.name.split('/').pop()])),norm=x=>String(x||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(dr|doctor|prof|professor)\.?\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim(),facultyIdByName=new Map();for(const f of faculty)for(const k of ['preferredFullName','hrFullName','hrFirstLast','teachingAssignmentName']){const n=field(f,k);if(n)facultyIdByName.set(norm(n),f.name.split('/').pop())}
 let removed=0,routed=0,writes=[];const now=new Date().toISOString();for(const f of faculty){const mask=[],fields={updatedBy:sv(actorUid),updatedByName:sv(actorName),updatedAt:tv(now)};mask.push('updatedBy','updatedByName','updatedAt');if(Object.prototype.hasOwnProperty.call(f.fields||{},'assignedAD')){mask.push('assignedAD');removed++}const target=facultyIdByName.get(norm(field(f,'reportsTo'))),route=target&&uidByFaculty.get(target);if(route&&field(f,'reportToUid')!==route){mask.push('reportToUid');fields.reportToUid=sv(route);routed++}if(mask.length>3)writes.push({update:{name:f.name,fields},updateMask:{fieldPaths:mask}})}
 for(let i=0;i<writes.length;i+=300)await api(`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents:commit`,{method:'POST',body:JSON.stringify({writes:writes.slice(i,i+300)})});
 const id=()=>crypto.randomBytes(10).toString('hex'),resource=`projects/${project}/databases/(default)/documents`,marker=`${resource}/settings/migrations_assigned_ad_removed`,account=`${resource}/account_audit/${id()}`,facultyLog=`${resource}/faculty_change_log/${id()}`,common={changedBy:sv(actorUid),changedByName:sv(actorName),changedAt:tv(now)};
 const finalWrites=[{update:{name:marker,fields:{completedAt:tv(now),completedBy:sv(actorUid),removed:iv(removed),routed:iv(routed)}},currentDocument:{exists:false}},{update:{name:account,fields:{action:sv('faculty_routing_migration'),removedAssignedAD:iv(removed),reportToRoutes:iv(routed),...common}},currentDocument:{exists:false}},{update:{name:facultyLog,fields:{action:sv('remove_assigned_ad_and_build_report_to_routes'),facultyCount:iv(faculty.length),removedAssignedAD:iv(removed),reportToRoutes:iv(routed),...common}},currentDocument:{exists:false}}];await api(`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents:commit`,{method:'POST',body:JSON.stringify({writes:finalWrites})});console.log(JSON.stringify({ok:true,alreadyDone:false,faculty:faculty.length,removed,routed,updatedDocuments:writes.length}))})().catch(e=>{console.error(e.message);process.exit(1)});
